Repository Jip-coon/Jip-coon, pull requests merged in 2025-08, with the labels that each got.

#3 Update .gitignore
  .gitignore
Labels: ⚙ Setting

#4 Delete Jip-coon/Jip-coon/.gitignore
  Jip-coon/.gitignore
Labels: ⚙ Setting

#10 #9/main view controller
  Jip-coon/Project.swift
  Jip-coon/Projects/App/Project.swift
  Jip-coon/Projects/App/Sources/AppDelegate.swift
  Jip-coon/Projects/App/Sources/SceneDelegate.swift
  Jip-coon/Projects/Feature/Scenes/MainView/MainViewController.swift
Labels: ✨ Feature

#14 #13/icon 앱 아이콘 추가
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120 1.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Jip-coon/Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Jip-coon/Projects/Feature/Scenes/MainView/MainViewController.swift
  Jip-coon/Projects/UI/Sources/Extensions/ColorExtension.swift
Labels: 🎨 Design

#21 #19/fireauth login
  Jip-coon/Projects/App/Project.swift
  Jip-coon/Projects/App/Resources/GoogleService-Info.plist
  Jip-coon/Projects/App/Sources/AppDelegate.swift
  Jip-coon/Projects/App/Sources/SceneDelegate.swift
  Jip-coon/Projects/Core/Project.swift
  Jip-coon/Projects/Core/Sources/Auth/AuthService.swift
  Jip-coon/Projects/Core/Sources/Auth/AuthServiceProtocol.swift
  Jip-coon/Projects/Feature/Project.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/View/LoginView.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/View/LoginViewController.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/ViewModel/LoginViewModel.swift
  Jip-coon/Projects/Feature/Scenes/MainScene/MainViewController.swift
  Jip-coon/Projects/UI/Project.swift
  Jip-coon/Tuist/Package.swift
Labels: ✨ Feature

#22 #20/회원가입 뷰 만들기
  Jip-coon/Projects/App/Sources/SceneDelegate.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/View/LoginView.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/View/LoginViewController.swift
  Jip-coon/Projects/Feature/Scenes/SignUpScene/View/SignUpViewController.swift
  Jip-coon/Projects/Feature/Scenes/SignUpScene/ViewModel/SignUpViewModel.swift
  Jip-coon/Projects/UI/Resources/Colors.xcassets/textRed.colorset/Contents.json
  Jip-coon/Projects/UI/Sources/Extensions/ColorExtension.swift
Labels: ✨ Feature

#24 #23/애플 로그인
  Jip-coon/Projects/App/Jip-coon.entitlements
  Jip-coon/Projects/App/Project.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/View/LoginViewController.swift
  Jip-coon/Projects/Feature/Scenes/LoginScene/ViewModel/AppleLoginViewModel.swift
  Jip-coon/Projects/Jip-coon.entitlements
Labels: ✨ Feature
